### ISSUE TITLE
Dimension of glasses for 3D printing

### ISSUE THREAD

**Issue by phuccuongngo99** [mahmoods01/agns#1]
Thank you so much for such amazing paper and this open-source code.

I am interested in replicating physical attack against vgg and open-face:
Can you provide more instructions on the dimension of the glasses to be 3D printed as well as how to place the green markers on the glasses.

Thank you once again

**Comment by mahmoods01** [comment]
You're welcome!

The width of the eyeglasses we used for the experiments is ~13cm. The other dimensions should be scaled proportionally. As for the green marks, you should try to position them roughly the same as in [this image](https://github.com/mahmoods01/agns/blob/master/data/demo-data2/aligned_vgg_ms1.png?raw=true). The alignment will be imperfect anyway, but the code will attempt to minimize the sum of errors.

**Comment by phuccuongngo99** [comment]
Thank you
I am grateful if you can attach the 3D printing file

**Comment by mahmoods01** [comment]
Sure, PFA.

[glasses-with-thicker-temples.ply.zip](https://github.com/mahmoods01/agns/files/3191121/glasses-with-thicker-temples.ply.zip)
