### ISSUE TITLE
Running demo.m - where is the generator?

### ISSUE THREAD

**Issue by bunni90** [mahmoods01/agns#5]
Hi everyone,
thanks for this open source project. I am having troubles running `demo.m`, I get an error that there is no file `models/gen.mat`. I downloaded the models from https://tinyurl.com/AGNsModels - as advised in the readme, but there is no file `gen.mat`. What can I use as the generator model? Or where can I download it? The same issue is with the disriminator `discrim.mat`.
Thanks in advance

**Comment by bunni90** [comment]
Hi everyone,
so I trained my own generator and discriminator with this model https://github.com/sunghbae/dcgan-matconvnet, but when I use these I get the error "Reference to non-existent field 'matrices'.". The generator (and discriminator respectivley) do not have this filed matrices. Could you provide me the link which model to use to get a generator which is compatible with this code?
Thanks in advance

**Comment by mahmoods01** [comment]
Hi, @bunni90. I added the missing models' weights (`gen.mat` and `discrim.mat`) to the `.tgz` archive and re-uploaded. Please re-download the archive from https://tinyurl.com/AGNsModels and test again.

**Comment by bunni90** [comment]
Thank you very much. I really appreciate it.
